title: API Specification Toolbox - News
description: An API-driven toolbox for building and managing APIs using common API specifications, providing a variety of resources about API specifications and how they are being put to use across the API lifecycle.
tagline: Building Awareness of API Specifications
image: images/network-logo.png
url: https://postman-toolboxes2.github.io/service-providers
twitter: APISpecToolbox

email: info@apievangelist.com

github_user: api-network
github_repo: template
github_branch: master

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

collections:
  news:
    output: true
    permalink: /news/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      type: news
    values:
      layout: news
  - scope:
      type: tags
    values:
      layout: tags